package com.zhao.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("roles_permissions", "id", RolesPermissions.class);
		arp.addMapping("task", "id", Task.class);
		arp.addMapping("test", "id", Test.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_roles", "id", UserRoles.class);
		arp.addMapping("users", "id", Users.class);
	}
}

