package com.zhao.model;

import com.zhao.model.base.BaseUserRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRoles extends BaseUserRoles<UserRoles> {
	public static final UserRoles dao = new UserRoles().dao();
}
