package com.zhao.model;

import com.zhao.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static String Vstatic="Vstatic";
	public static final User dao = new User().dao();
}
